module CuffSert
  INPROGRESS_STATES = %[
    CREATE_IN_PROGRESS
    UPDATE_IN_PROGRESS
    DELETE_IN_PROGRESS
  ]

  FINAL_STATES = %[
    CREATE_COMPLETE
    CREATE_FAILED
    ROLLBACK_COMPLETE
  ]
end
