module CuffSert
  INPROGRESS_STATES = %w[
    CREATE_IN_PROGRESS
    UPDATE_IN_PROGRESS
    UPDATE_COMPLETE_CLEANUP_IN_PROGRESS
    DELETE_IN_PROGRESS
  ]

  FINAL_STATES = %w[
    CREATE_COMPLETE
    CREATE_FAILED
    ROLLBACK_COMPLETE
    UPDATE_COMPLETE
    UPDATE_FAILED
    DELETE_COMPLETE
    DELETE_FAILED
    DELETE_SKIPPED
  ]
end
